title: 文庫
timezone: Asia/Shanghai

markdown: redcarpet

footers:
  - hant: 關於
    hans: 关于
    url: "/about"
  - hant: 幫助
    hans: 帮助
    url: "/help"

exclude:
  - README.md
  - Makefile
  - fetch.py
