title: 文庫
timezone: Asia/Shanghai

markdown: redcarpet

footers:
  - title:
      hant: 關於
      hans: 关于
    url:
      hant: "/zh-hant/about"
      hans: "/zh-hans/about"
  - title:
      hant: 幫助
      hans: 帮助
    url:
      hant: "/zh-hant/help"
      hans: "/zh-hans/help"

exclude:
  - README.md
  - Makefile
  - fetch.py
